// Code generated by internal/tagresource/generator/main.go; DO NOT EDIT.

package aws

import (
	"fmt"
	"log"

	"github.com/hashicorp/terraform-plugin-sdk/helper/schema"
	"github.com/terraform-providers/terraform-provider-aws/aws/internal/keyvaluetags"
	"github.com/terraform-providers/terraform-provider-aws/aws/internal/tagresource"
)

func resourceAwsRoute53Tag() *schema.Resource {
	return &schema.Resource{
		Create: resourceAwsRoute53TagCreate,
		Read:   resourceAwsRoute53TagRead,
		Update: resourceAwsRoute53TagUpdate,
		Delete: resourceAwsRoute53TagDelete,
		Importer: &schema.ResourceImporter{
			State: schema.ImportStatePassthrough,
		},

		Schema: map[string]*schema.Schema{
			"resource_id": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
			},
			"key": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
			},
			"value": {
				Type:     schema.TypeString,
				Required: true,
			},
		},
	}
}

func resourceAwsRoute53TagCreate(d *schema.ResourceData, meta interface{}) error {
	conn := meta.(*AWSClient).route53conn

	identifier := d.Get("resource_id").(string)
	key := d.Get("key").(string)
	value := d.Get("value").(string)

	if err := keyvaluetags.Route53UpdateTags(conn, identifier, nil, map[string]string{key: value}); err != nil {
		fmt.Errorf("error creating route53 resource (%s) tag (%s): %w", identifier, key, err)
	}

	d.SetId(tagresource.SetResourceId(identifier, key))

	return resourceAwsRoute53TagRead(d, meta)
}

func resourceAwsRoute53TagRead(d *schema.ResourceData, meta interface{}) error {
	conn := meta.(*AWSClient).route53conn
	identifier, key, err := tagresource.GetResourceId(d.Id())

	if err != nil {
		return err
	}

	exists, value, err := keyvaluetags.Route53GetTag(conn, identifier, key)

	if err != nil {
		fmt.Errorf("error reading route53 resource (%s) tag (%s): %w", identifier, key, err)
	}

	if !exists {
		log.Printf("[WARN] route53 resource (%s) tag (%s) not found, removing from state", identifier, key)
		d.SetId("")
		return nil
	}

	d.Set("resource_id", identifier)
	d.Set("key", key)
	d.Set("value", value)

	return nil
}

func resourceAwsRoute53TagUpdate(d *schema.ResourceData, meta interface{}) error {
	conn := meta.(*AWSClient).route53conn
	identifier, key, err := tagresource.GetResourceId(d.Id())

	if err != nil {
		return err
	}

	if err := keyvaluetags.Route53UpdateTags(conn, identifier, nil, map[string]string{key: d.Get("value").(string)}); err != nil {
		return fmt.Errorf("error updating route53 resource (%s) tag (%s): %w", identifier, key, err)
	}

	return resourceAwsRoute53TagRead(d, meta)
}

func resourceAwsRoute53TagDelete(d *schema.ResourceData, meta interface{}) error {
	conn := meta.(*AWSClient).route53conn
	identifier, key, err := tagresource.GetResourceId(d.Id())

	if err != nil {
		return err
	}

	if err := keyvaluetags.Route53UpdateTags(conn, identifier, map[string]string{key: d.Get("value").(string)}, nil); err != nil {
		return fmt.Errorf("error deleting route53 resource (%s) tag (%s): %w", identifier, key, err)
	}

	return nil
}
